version: '3.8'
services:
  slave0:
    container_name: slave0
    build: .
    shm_size: 2gb  # Increase the size of /dev/shm
    command: ["mpiexec", "-np", "17", "--hostfile", "/app/hostfile", "python3", "/app/slave.py"]
    volumes:
      - ./hostfile:/app/hostfile
      - ./:/app/
  slave1:
    container_name: slave1
    build: .
    shm_size: 2gb
  slave2:
    container_name: slave2
    build: .
    shm_size: 2gb
  slave3:
    container_name: slave3
    build: .
    shm_size: 2gb
  slave4:
    container_name: slave4
    build: .
    shm_size: 2gb
