version: '3.8'
services:
  node1:
    build: .
    networks:
      - mpi_network

  node2:
    build: .
    networks:
      - mpi_network

  node3:
    build: .
    networks:
      - mpi_network
      
  node4:
    build: .
    networks:
      - mpi_network

networks:
  mpi_network:
    driver: bridge