version: '3.7'

services:
  mpi-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    image: mpi-python-master
    container_name: mpi-master
    volumes:
      - shared-keys:/root/.ssh
    networks:
      - mpi-net

  mpi-node-1:
    build:
      context: .
      dockerfile: Dockerfile.nodes
    image: mpi-python-worker
    container_name: mpi-node-1
    volumes:
      - shared-keys:/shared-keys
    networks:
      - mpi-net
    depends_on:
      - mpi-master

  mpi-node-2:
    build:
      context: .
      dockerfile: Dockerfile.nodes
    image: mpi-python-worker
    container_name: mpi-node-2
    volumes:
      - shared-keys:/shared-keys
    networks:
      - mpi-net
    depends_on:
      - mpi-master

  mpi-node-3:
    build:
      context: .
      dockerfile: Dockerfile.nodes
    image: mpi-python-worker
    container_name: mpi-node-3
    volumes:
      - shared-keys:/shared-keys
    networks:
      - mpi-net
    depends_on:
      - mpi-master

  mpi-node-4:
    build:
      context: .
      dockerfile: Dockerfile.nodes
    image: mpi-python-worker
    container_name: mpi-node-4
    volumes:
      - shared-keys:/shared-keys
    networks:
      - mpi-net
    depends_on:
      - mpi-master

volumes:
  shared-keys:

networks:
  mpi-net:
    driver: bridge