version: '3.8'
services:
  slave1:
    build: .
    container_name: slave1
    networks:
      - mpi_network
  slave2:
    build: .
    container_name: slave2
    networks:
      - mpi_network
  slave3:
    build: .
    container_name: slave3
    networks:
      - mpi_network
  slave4:
    build: .
    container_name: slave4
    networks:
      - mpi_network

networks:
  mpi_network:
    driver: bridge
